### PR TITLE
Remove Read the Docs integration

### PR DESCRIPTION
**Pull request by christopherwoodall**
We are planning to remove support for `readthedocs` and shift towards using plain markdown files for our documentation.

## Reasoning:
  - Simplified Workflow: By using plain markdown files, we eliminate the need for maintaining a separate platform and syncing changes. This will make the documentation process more straightforward and efficient.
  - Version Control: Managing documentation directly through markdown files allows us to leverage the full power of version control systems like Git. This means easy tracking of changes, collaborative editing, and enhanced traceability.
  - Better Accessibility: Rendering markdown files is supported natively on most platforms, ensuring better accessibility for our contributors and users alike.

## Tasks to be Completed:
- [ ] Close the repository's `readthedocs` account.
- [x] Update the README and any relevant contribution guidelines to reflect the new documentation setup.
- [x] Archive or migrate any valuable content from `readthedocs` to our new markdown-based system.
- [x] Conduct thorough testing to ensure the documentation appears as intended in the new format.

## Timeline:
We aim to complete the transition NLT the end of the week. However, we understand that unforeseen challenges might arise, so we'll closely monitor the progress and adjust the timeline accordingly.

### CODE REVIEW

**Comment by mwartell** [comment]
I question the value of readthedocs now that Github markdown support has gotten so capable and Github pages can fill any gaps left. Fewer dependencies are better. Fewer sites that we need to talk to to make docs are better.

**Comment by christopherwoodall** [comment]
Paused until `pyyaml` [issues](https://github.com/yaml/pyyaml/issues/724)[[2](https://github.com/yaml/pyyaml/issues/601)] are resolved.

**Comment by christopherwoodall** [comment]
See issue thread in [tensorflow/models#11051](https://github.com/tensorflow/models/issues/11051)

**Review by mwartell — APPROVED** [review]
I love it.

**Pull request merged**
