### PR TITLE
enable configurable tensorflow c++ logging

### LINKED ISSUE #1743: Enable handling of tensorflow c++ log messages (which are printed to stdout)
TensorFlow has both python and c++ logging. We currently handle the python logging, but not c++, which is why we get outputs like this:
```
2022-11-04 18:33:21.033605: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-04 18:33:21.219144: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-04 18:33:22.094346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/
2022-11-04 18:33:22.094493: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/
2022-11-04 18:33:22.094526: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Executing: tfds build /workspace/armory/datasets/adversarial/carla_over_obj_det_dev --data_dir /armory/datasets/new_builds --force_checksums_validation
2022-11-04 18:33:23.946346: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-04 18:33:24.127490: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-04 18:33:24.918559: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/
2022-11-04 18:33:24.918684: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/
2022-11-04 18:33:24.918711: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-11-04 18:33:26.564730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib/
2022-11-04 18:33:26.564795: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-11-04 18:33:26.564831: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bcd5b4748ff6): /proc/driver/nvidia/version does not exist
```

### PR DESCRIPTION
**Pull request by davidslater**
Fixes #1743

@mwartell I'd like you to look at what I'm doing here, since you understand what `loguru` is doing behind the scenes.

### CODE REVIEW

**Comment by davidslater** [comment]
I think the environment variable needs to be set before tensorflow is loaded.

**Comment by mwartell** [comment]
The execution order of `logs.py` is intentionally high in order to happen before imports.  That is, `import logs` is the second line (below `import Pathlib`) so that few imports can happen above.  Testing this pull request now.

**Comment by mwartell** [comment]
Another instance of the "Armory has two Mains" issue. The command-line needs to be reformulated for passing from `armory run` to  evaluator.run. The tensorflow_cpp directive needed to be passed along
```
--- a/armory/logs.py
+++ b/armory/logs.py
@@ -135,6 +135,7 @@ def update_filters(specs: List[str], armory_debug=None):
 
         if key == "tensorflow_cpp":
             set_tensorflow_cpp_loglevel(level)
+            added_filters[key] = level
             continue
 
         try:
```

**Comment by davidslater** [comment]
@mwartell do the command line logging directives generally not get passed to scenarios main? Or is it only a specific subset of them?

**Comment by mwartell** [comment]
They all do. In the try block just after your change, they are added to `added_filters` for reconstruction. The patch line above adds the "tensorflow_cpp" directive to that reconstruction set.

**Comment by davidslater** [comment]
Ah, I follow now

**Comment by davidslater** [comment]
Updated

**Comment by christopherwoodall** [comment]
Should the environmental variable `TF_CPP_MIN_LOG_LEVEL` also be set in the dockerfile; e.g. `ENV TF_CPP_MAX_VLOG_LEVEL=0`

**Review by mwartell — APPROVED** [review]

**Pull request merged**
