### PR TITLE
Armory v0.17.2 release candidate

### PR DESCRIPTION
**Pull request by mwartell**
Placeholder for when ~#1942~ and #1939 (and others as wanted) are available.

- [x] Merge PR #1939 
- [x] Ensure `tools/runs_scenarios.sh` is removed

### CODE REVIEW

**Comment by mwartell** [comment]
@jprokos26 Sterling requested we hold this until #1939 is complete.

**Comment by swsuggs** [comment]
To be clear, I do want 1942 in here too.  I was just giving myself until 1939 was ready to see if I found anything else that needed fixing

**Comment by swsuggs** [comment]
> @jprokos26 Sterling requested we hold this until #1939 is complete.

There's no rush by the way, next week would be fine

**Review by swsuggs — APPROVED** [review]
Looks great

**Pull request merged**
