### PR TITLE
eval5 configs for asr (and bug fixes)

### PR DESCRIPTION
**Pull request by davidslater**
Partially solves #1374

### CODE REVIEW

**Comment by davidslater** [comment]
Note that you will have to do this first before running the configs.
```
bash docker/build-base.sh
python docker/build.py pytorch-deepspeech --no-pull
```
For checking, I recommend setting `max_iter` to 1.

**Comment by lcadalzo** [comment]
Did you mean to push a config with `max_iter` set to 1? [Here](https://github.com/davidslater/armory/blob/eval5-asr-configs/scenario_configs/eval5/asr_librispeech/defended_entailment.json#L12)

**Comment by lcadalzo** [comment]
What bug fixes does this address? Is there a separate issue for them?

**Comment by lcadalzo** [comment]
I did just finish confirming that I can run all the configs in `eval5/asr_librispeech` successfully with `--check`

**Comment by swsuggs** [comment]
I can run as well.  Anything specific we should check for in the output?

**Comment by swsuggs** [comment]
entailment.json and defended_entailment.json both have `"num_eval_batches": 100` in the config, was that intentional?

**Comment by lcadalzo** [comment]
> entailment.json and defended_entailment.json both have `"num_eval_batches": 100` in the config, was that intentional?

yes, that I know is intentional (I had asked the same question previously)

**Comment by lcadalzo** [comment]
On the develop branch I've run into this error, related to the parts of the code that this PR changes. Not sure if this is the only bug we were tracking though:

```
File "/workspace/armory/instrument/config.py", line 228, in _write
result = metrics.get_supported_metric("total_entailment")(result)
         │       │                                        └ ['entailment']
         │       └ <function get_supported_metric at 0x7fdb66ed8670>
         └ <module 'armory.utils.metrics' from '/workspace/armory/utils/metrics.py'>
File "/workspace/armory/utils/metrics.py", line 104, in total_entailment
for i in range(sample_results):
               └ ['entailment']
TypeError: 'list' object cannot be interpreted as an integer

```

**Comment by davidslater** [comment]
@lcadalzo I hadn't made issues for the bugs. There are two:
1) The error you noted:
```
result = metrics.get_supported_metric("total_entailment")(result)
         │       │                                        └ ['entailment']
```
2) The mp3 compression defense requires the `pydub` library. We had removed this from the base docker image because we couldn't figure out what is was for.

**Comment by lcadalzo** [comment]
@davidslater should all ASR configs go in either the `eval1-4` or `eval5` folder? That's what we did for the other scenarios (if you look at the develop branch, you'll see the only files not in said folders are ASR ones to be moved in this PR)

**Review by lcadalzo — CHANGES_REQUESTED** [review]
requesting that we move all librispeech configs to either the `eval1-4` or `eval5` dir

**Comment by davidslater** [comment]
@lcadalzo done

**Comment by lcadalzo** [comment]
@davidslater looks like there's still one file in the base:

https://github.com/davidslater/armory/blob/eval5-asr-configs/scenario_configs/speaker_id_librispeech_snr_pgd.json

**Comment by davidslater** [comment]
Good catch, fixed.

**Comment by lcadalzo** [comment]
LGTM

**Pull request merged**
