### PR TITLE
migrate adaptive attack tutorial

### PR DESCRIPTION
**Pull request by lcadalzo**
See #1402

### CODE REVIEW

**Comment by lcadalzo** [comment]
This PR would add a `tutorials/` directory. We may want to move `notebooks/` inside this directory

**Comment by davidslater** [comment]
@swsuggs can you review?

**Comment by swsuggs** [comment]
@lcadalzo  did these run for you?  I ran `armory run tutorials/adaptive_attacks/custom_attack.json` and got this error:
```
File "/workspace/armory/scenarios/scenario.py", line 345, in run_attack
x_adv = self.attack.generate(x=x, y=y_target, **self.generate_kwargs)
        │    │      │          │    │           │    └ {}
        │    │      │          │    │           └ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7f347d233910>
        │    │      │          │    └ None
        │    │      │          └ array([[[[0.7058824 , 0.7294118 , 0.7411765 ],
        │    │      │                     [0.6313726 , 0.654902  , 0.65882355],
        │    │      │                     [0.54901963, 0.5725490...
        │    │      └ <function CustomAttack.generate at 0x7f334066cc10>
        │    └ <custom_attack.CustomAttack object at 0x7f3342fd41c0>
        └ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7f347d233910>
File "/armory/git/swsuggs/armory/tutorials/adaptive_attacks/custom_attack.py", line 10, in generate
for x_sample, y_sample in zip(x, y):
                              │  └ None
                              └ array([[[[0.7058824 , 0.7294118 , 0.7411765 ],
                                         [0.6313726 , 0.654902  , 0.65882355],
                                         [0.54901963, 0.5725490...
TypeError: 'NoneType' object is not iterable
```
The scenario passes None to the custom attack for y, because the attack is untargeted.  I think `use_label` needs to be true in the config?

**Comment by lcadalzo** [comment]
> The scenario passes None to the custom attack for y, because the attack is untargeted. I think use_label needs to be true in the config?

`"targeted"` was supposed to be set to `true`, so that it uses the label targeter. Armory doesn't let you set `"targeted"` and `"use_label"` both as `true`

**Review by swsuggs — APPROVED** [review]
Cool, everything looks good

**Comment by davidslater** [comment]
How would you distinguish between notebooks and tutorials? Would all notebooks be a form of tutorial?

**Comment by lcadalzo** [comment]
I think it's likely notebooks are tutorials, but I suppose they need not be. In that case, we can keep the flatter structure as it's currently organized

**Comment by swsuggs** [comment]
I agree that makes sense

**Pull request closed without merging**
