### PR TITLE
add standard github citation info

### LINKED ISSUE #1865: How to properly cite armory?
Hi! Armory has come up a few times as I review literature for my dissertation, and I'd like to properly reference it when I discuss it. Papers I've found that utilize it seem to cite it inconsistently, such as citing other papers that discuss it rather than the project itself, or leaving a link to some part of the github rather than a full citation. Since these references are inconsistent, I've also had a harder time tracking down research papers that utilize it. Some of the similar toolkits I've looked at (such as https://github.com/QData/TextAttack) have preferred citation information in their readme, but I didn't see anything here and didn't find anything obvious in my searches online either. Is there a preferred method for this?

My first thoughts were to either cite this github directly (although I've seen different papers cite different pages of it, which makes search more difficult), or this webpage (https://www.darpa.mil/news-events/2021-12-21) that describes the project a bit. I wanted to ask if there was a preference, and to suggest that the answer be added to the readme such that a convention becomes established for future publications. There's some impressive work being done with this, and I'd like to ensure you all get the credit you deserve!

Thanks.

### PR DESCRIPTION
**Pull request by mwartell**
Fixes #1865

### CODE REVIEW

**Comment by mwartell** [comment]
This is merging directly to `master` since these metadata changes need to be in that branch to be visible on Github.

**Comment by lcadalzo** [comment]
> @lcadalzo Please suggest keywords for the citation.

I'd change "adversarial ml" to "adversarial machine learning"

**Comment by lcadalzo** [comment]
@mwartell lgtm, any other potential changes before we merge?

**Comment by mwartell** [comment]
It is ready to go, just needs your approval.

**Review by lcadalzo — APPROVED** [review]

**Pull request merged**
