### PR TITLE
tfdsv4 so2sat

### PR DESCRIPTION
**Pull request by lcadalzo**
to build so2sat dataset:

```
python -m armory.datasets.build so2sat --register_checksums
```

### CODE REVIEW

**Comment by lcadalzo** [comment]
using `package.add_to_cache()` errors out because the directory structure of so2sat doesn't match what Armory is expecting:

```
>>> from armory.datasets import package
>>> package.add_to_cache("so2sat", public=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/armory/datasets/package.py", line 136, in add_to_cache
    package(
  File "/workspace/armory/datasets/package.py", line 28, in package
    raise FileNotFoundError(f"Dataset {name} not found at {expected_dir}")
FileNotFoundError: Dataset so2sat not found at /armory/datasets/new_builds/so2sat/2.1.0

```

Looking at the directory structure: 
```

I have no name!@467325c59ab6:/workspace$ ls /armory/datasets/new_builds/so2sat/
all  rgb
I have no name!@467325c59ab6:/workspace$ ls /armory/datasets/new_builds/so2sat/all/
2.1.0
I have no name!@467325c59ab6:/workspace$ ls /armory/datasets/new_builds/so2sat/rgb/   
2.1.0
```

**Comment by lcadalzo** [comment]
@ppark-twosixtech I'm now able to build and `add_to_cache()` after the updates in your imagenette PR were merged to `tfdsv4`. I'm currently uploading to s3. As a heads up, the dataset is ~27GB so may take a while to run

**Comment by lcadalzo** [comment]
CI tests: https://github.com/lcadalzo/armory/actions/runs/4085350684

**Comment by lcadalzo** [comment]
@ppark-twosixtech you should be able to test this now and run a scenario successfully. I'm not quite sure why CI is failing (linked above) but it doesn't appear related to the changes in this PR. We can hold off on merging until that's investigated, but you should be able to re-review

**Comment by ppark-twosixtech** [comment]
Checked with https://github.com/twosixlabs/armory/blob/master/scenario_configs/eval1-4/so2sat/so2sat_eo_masked_pgd_undefended.json, which also downloaded the dataset from S3 - LGTM

**Pull request merged**
