### PR TITLE
update carla object detection patch attack to increase its efficacy

### PR DESCRIPTION
**Pull request by yusong-tan**

### CODE REVIEW

**Comment by lcadalzo** [comment]
There's a comment in the code on dev branch which this PR would remove:
```
 #must be square for now, until it's determined why non-square patches fail to completely overlay green screen
```

Has it been determined this (non-square patches failing to completely overlay green screen) is no longer an issue?

**Comment by yusong-tan** [comment]
@lcadalzo It's still an issue for DAPRICOT dataset due to a constraint on the rectangle aspect ratio, but this issue doesn't apply to the CARLA dataset.

**Comment by lcadalzo** [comment]
@yusong-tan what effect on results did you observe the changes in this PR to have?

**Comment by yusong-tan** [comment]
@lcadalzo I don't have metrics such as mAP. Prior to the change, it was difficult to generate any hallucinated objects. After the change, one can usually produce one or more hallucinated objects per patch, under the same attack parameters. Disappearances/misclassifications are minimally impacted by the change, primarily because they are generally more difficult to produce in the first place.

**Review by lcadalzo — APPROVED** [review]
LGTM

**Pull request merged**
