### PR TITLE
fix numpy ci failures

### PR DESCRIPTION
**Pull request by lcadalzo**
Addressing CI failures from #1832 resulting from jump to numpy 1.24

### CODE REVIEW

**Comment by lcadalzo** [comment]
@mwartell this PR does not intend to address any of the numba issues (as I understand you're working on that). The sole purpose of this PR is to fix the numpy CI failures

**Review by mwartell — APPROVED** [review]
Good pending tests. Those are some pretty basic interface elements to change in a numpy minor release.

**Comment by lcadalzo** [comment]
Linking the Scenario Runner tests [here](https://github.com/lcadalzo/armory/actions/runs/3752128457). I would expect these to fail due to numba incompatibility with numpy 1.24.0, although...

@mwartell do you know the expected behavior of Scenario Runner if the config JSON's it runs are using `twosixarmory:pytorch` and `twosixarmory:carla-mot`, etc. images that are no longer built by `develop` after we consolidated images? Will it simply pull the `twosixarmory:pytorch:0.16.1` image? If so, I'd expect Scenario Runner to pass since that has numpy 1.23

**Review by mwartell — APPROVED** [review]

**Comment by mwartell** [comment]
@lcadalzo Yes that is the proper expectation.

**Pull request merged**
