### PR TITLE
WIP: Major revamp

### PR DESCRIPTION
**Pull request by shenshaw26**
Working to separate Launcher from execution engine.  

Started with MNIST Baseline:
`armory-launcher -v run ./tests/scenarios/experiments/base_image_classification.aexp  --override model.fit_kwargs.nb_epochs=1 --override execution.mode=native` which as of `3d80805b13868943a2dc61db89ff45dc1277b661` worked successfully

### CODE REVIEW

**Comment by shenshaw26** [comment]
@davidslater, still a long way to go here, but this at least works with baseline MNIST

**Comment by davidslater** [comment]
@shenshaw26 can you update to black 22.3? (This was part of the 0.15.0 release update). It will make it a lot easier to parse the changes you've made here.

**Comment by shenshaw26** [comment]
> @shenshaw26 can you update to black 22.3? (This was part of the 0.15.0 release update). It will make it a lot easier to parse the changes you've made here.

Will do!!

**Comment by davidslater** [comment]
I'm having a hard time parsing the changes - it won't even load in my browser. Can you point me to the most relevant files?

**Comment by mwartell** [comment]
Obsoleted by #1696 which aims for the same goal with a more staged approach than was done here.

**Pull request closed without merging**
