### PR TITLE
Fix missing validation folder in whl

### PR DESCRIPTION
**Pull request by kevinmerchant**

### CODE REVIEW

**Review by mwartell — COMMENTED** [review]
I have confirmed that `armory/validation/test_config/pytest.ini` and the two new __init__ files are built into the sdist and wheel as expected.

**Comment by davidslater** [comment]
Can we point this at `dev`, and see if this can merge in there?

**Comment by mwartell** [comment]
> Can we point this at `dev`, and see if this can merge in there?

Yeah. I saw this this morning and wondered why it had not been. I think the answer is "cuz we didn't have a dev branch".

**Review by mwartell — APPROVED** [review]
LGTM, CI passes and narrow extent.

**Pull request merged**
