### PR TITLE
Update dependencies for TF Object Detection API

### PR DESCRIPTION
**Pull request by ng390**

### CODE REVIEW

**Comment by ng390** [comment]
To test:
1. build docker containers
2. armory launch the tf1/tf2 image
3. Inside the container run
``python /opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder_tf1_test.py``
for the TF1 container 
and run
``python /opt/conda/lib/python3.7/site-packages/object_detection/builders/model_builder_tf2_test.py``
for the TF2 container

**Comment by ng390** [comment]
Neal to incorporate tests into CI testing

**Comment by ng390** [comment]
@kevinmerchant Ready for review

**Review by kevinmerchant — APPROVED** [review]
LGTM

**Pull request merged**
