### PR TITLE
fast untarring when possible

### LINKED ISSUE #802: Speed up cache dataset extraction
Python implementation is really slow compared to command line usage. (About 10x slower.)

https://github.com/twosixlabs/armory/blob/master/armory/data/utils.py#L271-L272

If tar is not available on the command line, falling back to python is okay, but my preference would be try the linux version first.

### PR DESCRIPTION
**Pull request by davidslater**
Fixes #802

### CODE REVIEW

**Comment by davidslater** [comment]
@mwartell I can't get the piping to work properly (it doesn't output files extracted, which would be nice, especially for very large files)

**Review by mwartell — APPROVED** [review]
LGTM.

absurdly trivial nitpick: verbose mode for tar is unneeded if we're just throwing the output away; mode "zxf" might save a few microseconds.

**Comment by davidslater** [comment]
I would ideally like to print the output, which I thought the stdout and stderr piping would do. Can you figure out why that's not happening?

**Comment by mwartell** [comment]
> I would ideally like to print the output, which I thought the stdout and stderr piping would do. Can you figure out why that's not happening?

It's because you didn't print it. The official docs often times get very cryptic, especially for subprocess. I made a quick stop at PYMOTW to confirm my recollection https://pymotw.com/3/subprocess/#capturing-output

You needed a `print(completedprocess.stdout.decode('utf-8'))` which I would add for you but I don't want to guess at your specific intention.

**Comment by davidslater** [comment]
Ready for re-review. Didn't realize removing those pipes would give me what I was looking for.

**Review by mwartell — APPROVED** [review]
LGTM. Less _is_ more.

**Pull request merged**
