### PR TITLE
remove unused import statement

### LINKED ISSUE #1291: armory.scenarios.main' found in sys.modules after import of package
/opt/conda/lib/python3.7/runpy.py:125: RuntimeWarning: 'armory.scenarios.main' found in sys.modules after import of package 'armory.scenarios', but prior to execution of 'armory.scenarios.main'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))

I've removed much irrelevance from this issue. This is the warning that I think should be hunted down and killed.

### PR DESCRIPTION
**Pull request by davidslater**
Fixes #1291

### CODE REVIEW

**Comment by davidslater** [comment]
I'm guessing that this import statement was used to enable this sort of gloss:
```
from armory import scenarios
scenarios.get("config_path.json")
```
But it doesn't look like it was ever used that way.

The import error happens because when loading the armory module, it essentially follows this order:
```
import armory/__init__.py
import armory/scenarios/__init__.py
# ^ This does: from armory.scenarios.main import get 
import armory/scenarios/main.py
```
hence the warning.

**Review by mwartell — APPROVED** [review]
Unrefed import is unrefed. LGTM.

**Comment by davidslater** [comment]
@mwartell you had meant to merge, not close, yes?

**Comment by mwartell** [comment]
Oops misclicked, thanks. 🤕

**Comment by mwartell** [comment]
This still needs to be imported into branch shenshaw26/duo. It should be brought in with the next merge of develop into duo.

**Pull request merged**
