### PR TITLE
apricot_dev

### PR DESCRIPTION
**Pull request by ppark-twosixtech**

### CODE REVIEW

**Comment by lcadalzo** [comment]
@ppark-twosixtech please update default configs

**Comment by lcadalzo** [comment]
I'm able to run with the following config:

```
 "attack": {
        "knowledge": "white",
        "kwargs": {
            "batch_size": 1,
            "split": "frcnn"
        },
        "module": "armory.data.adversarial_datasets",
        "name": "apricot_dev",
        "type": "preloaded",
        "use_label": false
    },
    "dataset": {
        "test": {
            "batch_size": 1,
            "name": "apricot_dev",
            "split": "frcnn"
        }
    },
    "defense": null,
    "eval_id": "2023-04-07T131205.204611",
    "metric": {
        "means": true,
        "perturbation": "linf",
        "record_metric_per_sample": false,
        "task": [
            "apricot_patch_targeted_AP_per_class",
            "object_detection_AP_per_class"
        ]
    },
    "model": {
        "fit": false,
        "fit_kwargs": {},
        "model_kwargs": {},
        "module": "armory.baseline_models.pytorch.mscoco_frcnn",
        "name": "get_art_model",
        "weights_file": null,
        "wrapper_kwargs": {}
    },
    "scenario": {
        "kwargs": {},
        "module": "armory.scenarios.object_detection",
        "name": "ObjectDetectionTask"
    },
    "sysconfig": {
        "docker_image": "twosixarmory/armory",
        "external_github_repo": null,
        "filepath": "scenario_configs/eval1-4/aprioct/apricot_frcnn.json",
        "gpus": "all",
        "interactive": true,
        "output_dir": null,
        "output_filename": null,
        "use_gpu": false
    }

```

**Comment by jprokos26** [comment]
Getting an error when running `apricot_frcnn.json`:

<details>
<summary>Toggle traceback</summary>

```
$ armory run scenario_configs/eval1-4/apricot/apricot_frcnn.json --check --gpus 0
2023-05-01 18:13:04  0s INFO     armory.__main__:_set_gpus:263 --gpus field specified. Setting --use-gpu to True
2023-05-01 18:13:04  0s INFO     armory.eval.evaluator:__init__:30 Constructing Evaluator Object
2023-05-01 18:13:04  0s INFO     armory.eval.evaluator:__init__:61 Retrieving Environment Variables
2023-05-01 18:13:04  0s INFO     armory.docker.images:ensure_image_present:160 Retrieved canonical image name for twosixarmory/armory as twosixarmory/armory:0.16.1.post394.g5730b932
2023-05-01 18:13:04  0s INFO     armory.docker.images:ensure_image_present:179 reverting to previous release tag image twosixarmory/armory:0.16.1
2023-05-01 18:13:04  0s SUCCESS  armory.docker.images:is_image_local:131 found docker image twosixarmory/armory:0.16.1
2023-05-01 18:13:05  0s INFO     armory.docker.management:__init__:62 ARMORY Instance a276577ff6cc created.
2023-05-01 18:13:05  0s INFO     armory.eval.evaluator:_run_config:269 Running evaluation script
2023-05-01 18:13:06  0s INFO     armory.delayed_imports:<module>:7 Importing and configuring torch, tensorflow, and art, if available. This may take some time.
2023-05-01 18:13:09  3s INFO     armory.delayed_imports:<module>:30 Setting tf.config.experimental.set_memory_growth to True on all GPUs
2023-05-01 18:13:09  3s INFO     art.config:set_data_path:55 set ART_DATA_PATH to /tmp/.art/data
2023-05-01 18:13:10  4s INFO     art.config:set_data_path:55 set ART_DATA_PATH to /armory/saved_models/art
2023-05-01 18:13:11  5s INFO     matplotlib.font_manager:_load_fontmanager:1624 generated new fontManager
/opt/conda/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
warnings.warn(
/opt/conda/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=FasterRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /armory/saved_models/pytorch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
2023-05-01 18:13:12  6s ERROR    armory.scenarios.scenario:evaluate:458 Encountered error during scenario evaluation.
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/urllib/request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
│ │       │   │             │   │         │   │     └ {'Host': 'download.pytorch.org', 'User-Agent': 'torch.hub', 'Connection': 'close'}
│ │       │   │             │   │         │   └ <property object at 0x7f5df57805e0>
│ │       │   │             │   │         └ <urllib.request.Request object at 0x7f5cd516f4c0>
│ │       │   │             │   └ '/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth'
│ │       │   │             └ <urllib.request.Request object at 0x7f5cd516f4c0>
│ │       │   └ <function Request.get_method at 0x7f5df5782c10>
│ │       └ <urllib.request.Request object at 0x7f5cd516f4c0>
│ └ <function HTTPConnection.request at 0x7f5df57791f0>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
│    │             │       │    │     │        └ False
│    │             │       │    │     └ {'Host': 'download.pytorch.org', 'User-Agent': 'torch.hub', 'Connection': 'close'}
│    │             │       │    └ None
│    │             │       └ '/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth'
│    │             └ 'GET'
│    └ <function HTTPConnection._send_request at 0x7f5df5779280>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
│    │          │                    └ False
│    │          └ None
│    └ <function HTTPConnection.endheaders at 0x7f5df5779160>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
│    │            │                            └ False
│    │            └ None
│    └ <function HTTPConnection._send_output at 0x7f5df5778d30>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 1040, in _send_output
self.send(msg)
│    │    └ b'GET /models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: download.pytorch.org\r...
│    └ <function HTTPConnection.send at 0x7f5df5778b80>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 980, in send
self.connect()
│    └ <function HTTPSConnection.connect at 0x7f5df5779430>
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/http/client.py", line 1447, in connect
super().connect()
File "/opt/conda/lib/python3.9/http/client.py", line 946, in connect
self.sock = self._create_connection(
│    │      │    └ <function create_connection at 0x7f5df62f3040>
│    │      └ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
│    └ None
└ <http.client.HTTPSConnection object at 0x7f5cd516f8b0>
File "/opt/conda/lib/python3.9/socket.py", line 844, in create_connection
raise err
└ None
File "/opt/conda/lib/python3.9/socket.py", line 832, in create_connection
sock.connect(sa)
│    │       └ ('2600:9000:24f2:1a00:d:607e:4540:93a1', 443, 0, 0)
│    └ <method 'connect' of '_socket.socket' objects>
└ <socket.socket [closed] fd=-1, family=Addres
sFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6>
OSError: [Errno 99] Cannot assign requested address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
│         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
│         └ <code object <module> at 0x7f5d119555b0, file "/workspace/armory/scenarios/main.py", line 1>
└ <function _run_code at 0x7f5df65999d0>
File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
│     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
└ <code object <module> at 0x7f5d119555b0, file "/workspace/armory/scenarios/main.py", line 1>
File "/workspace/armory/scenarios/main.py", line 229, in <module>
run_config(
└ <function run_config at 0x7f5d10844f70>
File "/workspace/armory/scenarios/main.py", line 145, in run_config
scenario.evaluate()
│        └ <function Scenario.evaluate at 0x7f5cdcfcf430>
└ <armory.scenarios.object_detection.ObjectDetectionTask object at 0x7f5d116ddeb0>
> File "/workspace/armory/scenarios/scenario.py", line 449, in evaluate
self._evaluate()
│    └ <function Scenario._evaluate at 0x7f5cdcfcf3a0>
└ <armory.scenarios.object_detection.ObjectDetectionTask object at 0x7f5d116ddeb0>
File "/workspace/armory/scenarios/scenario.py", line 438, in _evaluate
self.load()
│    └ <function Scenario.load at 0x7f5cdcfbfee0>
└ <armory.scenarios.object_detection.ObjectDetectionTask object at 0x7f5d116ddeb0>
File "/workspace/armory/scenarios/scenario.py", line 330, in load
self.load_model()
│    └ <function Scenario.load_model at 0x7f5cdcfbfa60>
└ <armory.scenarios.object_detection.ObjectDetectionTask object at 0x7f5d116ddeb0>
File "/workspace/armory/scenarios/scenario.py", line 160, in load_model
model, _ = config_loading.load_model(model_config)
           │              │          └ {'fit': False, 'fit_kwargs': {}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.mscoco_frcnn', 'name': 'get_ar...
           │              └ <function load_model at 0x7f5d108449d0>
           └ <module 'armory.utils.config_loading' from '/workspace/armory/utils/config_loading.py'>
File "/workspace/armory/utils/config_loading.py", line 112, in load_model
model = model_fn(
        └ <function get_art_model at 0x7f5cd7d1d310>
File "/workspace/armory/baseline_models/pytorch/mscoco_frcnn.py", line 34, in get_art_model
model = make_fastrcnn_model(weights_path=weights_path, **model_kwargs)

        │                                │               └ {}
        │                                └ None
        └ <function make_fastrcnn_model at 0x7f5cdcfcf940>
File "/workspace/armory/baseline_models/pytorch/mscoco_frcnn.py", line 22, in make_fastrcnn_model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
        │           │      │         └ <function fasterrcnn_resnet50_fpn at 0x7f5cd7d80550>
        │           │      └ <module 'torchvision.models.detection' from '/opt/conda/lib/python3.9/site-packages/torchvision/models/detection/__init__.py'>
        │           └ <module 'torchvision.models' from '/opt/conda/lib/python3.9/site-packages/torchvision/models/__init__.py'>
        └ <module 'torchvision' from '/opt/conda/lib/python3.9/site-packages/torchvision/__init__.py'>
File "/opt/conda/lib/python3.9/site-packages/torchvision/models/_utils.py", line 142, in wrapper
return fn(*args, **kwargs)
│   │       └ {'pretrained': True}
│   └ ()
└ <function fasterrcnn_resnet50_fpn at 0x7f5cd7d804c0>
File "/opt/conda/lib/python3.9/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
return builder(*args, **kwargs)
│        │       └ {'weights': FasterRCNN_ResNet50_FPN_Weights.COCO_V1}
│        └ ()
└ <function fasterrcnn_resnet50_fpn at 0x7f5cd7d80430>
File "/opt/conda/lib/python3.9/site-packages/torchvision/models/detection/faster_rcnn.py", line 565, in fasterrcnn_resnet50_fpn
model.load_state_dict(weights.get_state_dict(progress=progress))
│     │               │       │                       └ True
│     │               │       └ <function WeightsEnum.get_state_dict at 0x7f5cdc0e5af0>
│     │               └ FasterRCNN_ResNet50_FPN_Weights.COCO_V1
│     └ <function Module.load_state_dict at 0x7f5d691ceaf0>
└ FasterRCNN(
(transform): GeneralizedRCNNTransform(
Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
...
File "/opt/conda/lib/python3.9/site-packages/torchvision/models/_api.py", line 63, in get_state_dict
return load_state_dict_from_url(self.url, progress=progress)
│                        │                  └ True
│                        └ FasterRCNN_ResNet50_FPN_Weights.COCO_V1
└ <function load_state_dict_from_url at 0x7f5d68c3e0d0>
File "/opt/conda/lib/python3.9/site-packages/torch/hub.py", line 727, in load_state_dict_from_url
download_url_to_file(url, cached_file, hash_prefix, progress=progress)
│                    │    │            │                     └ True
│                    │    │            └ None
│                    │    └ '/armory/saved_models/pytorch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth'
│                    └ 'https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth'
└ <function download_url_to_file at 0x7f5d68c3cee0>
File "/opt/conda/lib/python3.9/site-packages/torch/hub.py", line 593, in download_url_to_file
u = urlopen(req)
│       └ <urllib.request.Request object at 0x7f5cd516f4c0>
└ <function urlopen at 0x7f5df58910d0>
File "/opt/conda/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
│      │    │    │     └ <object object at 0x7f5df67a5a10>
│      │    │    └ None
│      │    └ <urllib.request.Request object at 0x7f5cd516f
4c0>
│      └ <function OpenerDirector.open at 0x7f5df5783430>
└ <urllib.request.OpenerDirector object at 0x7f5cd516f4f0>
File "/opt/conda/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
│    │     │    └ None
│    │     └ <urllib.request.Request object at 0x7f5cd516f4c0>
│    └ <function OpenerDirector._open at 0x7f5df57834c0>
└ <urllib.request.OpenerDirector object at 0x7f5cd516f4f0>
File "/opt/conda/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
│    │           │    │            │         └ 'https'
│    │           │    │            └ 'https'
│    │           │    └ {'unknown': [<urllib.request.UnknownHandler object at 0x7f5cd516f640>], 'http': [<urllib.request.HTTPHandler object at 0x7f5c...
│    │           └ <urllib.request.OpenerDirector object at 0x7f5cd516f4f0>
│    └ <function OpenerDirector._call_chain at 0x7f5df57833a0>
└ <urllib.request.OpenerDirector object at 0x7f5cd516f4f0>
File "/opt/conda/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
│     └ (<urllib.request.Request object at 0x7f5cd516f4c0>,)
└ <bound method HTTPSHandler.https_open of <urllib.request.HTTPSHandler object at 0x7f5cd516f850>>
File "/opt/conda/lib/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
│    │       │    │      │                └ <urllib.request.Request object at 0x7f5cd516f4c0>
│    │       │    │      └ <class 'http.client.HTTPSConnection'>
│    │       │    └ <module 'urllib3.packages.six.moves.http_client' (<urllib3.packages.six._SixMetaPathImporter object at 0x7f5df57154f0>)>
│    │       └ <module 'http' from '/opt/conda/lib/python3.9/http/__init__.py'>
│    └ <function AbstractHTTPHandler.do_open at 0x7f5df5784e50>
└ <urllib.request.HTTPSHandler object at 0x7f5cd516f850>
File "/opt/conda/lib/python3.9/urllib/request.py", line 1349, in do_open
raise URLError(err)
└ <class 'urllib.error.URLError'>
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
2023-05-01 18:13:13  9s ERROR
```
</details>

**Review by jprokos26 — APPROVED** [review]
LGTM, finishes cleanly

**Pull request merged**
