### PR TITLE
Sleeper agent integration

### PR DESCRIPTION
**Pull request by swsuggs**
For #1583 

~~Currently waiting for bug fixes on the ART side.  There is some data transposition that breaks broadcasting for models with channels_first == False.~~

### CODE REVIEW

**Review by davidslater — COMMENTED** [review]
The code looks good. Currently running it.

I get nans for loss when retraining, though:
```
 name: Quadro RTX 6000, pci bus id: 0000:b1:00.0, compute capability: 7.5
2022-09-30 16:25:54 11s INFO     art.estimators.classification.pytorch:get_layers:1159 Inferred 1 hidden layers on PyTorch classifier.
2022-09-30 16:25:54 11s INFO     armory.scenarios.poisoning_sleeper_agent:load_poisoner:77 Fitting proxy model for attack . . .
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 125/125 [01:53<00:00,  1.10it/s, loss=nan]
2022-09-30 16:35:58 10m15s INFO     art.estimators.classification.pytorch:get_layers:1159 Inferred 1 hidden layers on PyTorch classifier.| 125/125 [01:53<00:00,  1.04it/s, loss=nan]
2022-09-30 16:44:44 19m INFO     art.attacks.poisoning.sleeper_agent_attack:_create_model:359 Accuracy of retrained model : 66.45
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 125/125 [01:42<00:00,  1.21it/s, loss=nan]
2022-09-30 16:46:28 20m45s INFO     art.estimators.classification.pytorch:get_layers:1159 Inferred 1 hidden layers on PyTorch classifier.| 125/125 [01:42<00:00,  1.17it/s, loss=nan]
```

**Comment by davidslater** [comment]
Ran into this issue:
```
    x_poison, y_poison = self.attack.poison(
                         │    │      └ <function SleeperAgentAttack.poison at 0x7f569bc2aaf0>
                         │    └ <art.attacks.poisoning.sleeper_agent_attack.SleeperAgentAttack object at 0x7f569bc44070>
                         └ <armory.scenarios.poisoning_sleeper_agent.DatasetPoisonerSleeperAgent object at 0x7f569bc44310>

  File "/tmp/.local/lib/python3.8/site-packages/art/attacks/poisoning/sleeper_agent_attack.py", line 241, in poison
    best_x_poisoned * self.substitute_classifier.preprocessing.std
                      │    │                     │             └ array(1., dtype=float32)
                      │    │                     └ StandardisationMeanStdPyTorch(mean=0.0, std=1.0, apply_fit=True, apply_predict=True, device=cuda:0)
                      │    └ art.estimators.classification.pytorch.PyTorchClassifier(model=ModelWrapper(
                      │        (_model): OuterModel(
                      │          (inner_model): ResNet...
                      └ <art.attacks.poisoning.sleeper_agent_attack.SleeperAgentAttack object at 0x7f569bc44070>

UnboundLocalError: local variable 'best_x_poisoned' referenced before assignment
```

I think this happens because the loss is nan.

**Comment by swsuggs** [comment]
Hm, that did happen to me once but it was a while ago so I figured it was fixed.  I will take a closer look

**Comment by davidslater** [comment]
I think it's probably an ART error

**Comment by davidslater** [comment]
I think it's an ART error - I made a bug report. https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/1865

**Pull request merged**
