### PR TITLE
updated dependencies

### LINKED ISSUE #227: Update dockerfile for dataset dependencies
Need the following:
ffmpeg (command line) - librispeech, ucf101 (and other audio/video)
pydub - librispeech (and other audio)
apache_beam - librispeech (and other big datasets)

### PR DESCRIPTION
**Pull request by davidslater**
fixes #227 

We will need to update the dockerfile on docker hub, though.

Currently testing locally to ensure all dependencies are resolved properly.

### CODE REVIEW

**Comment by davidslater** [comment]
Do we want to update the version to 0.5.1?

**Comment by ng390** [comment]
Keeping the ARMORY and Dockerfile versions in sync should simplify usage.

**Comment by davidslater** [comment]
Agreed. My question was about whether to stay on 0.5.0 for both or move to 0.5.1 (or 0.6.0) for both. With the latter, we'll need to push a new pypi package to test.

**Comment by davidslater** [comment]
Once the docker PR gets merged, I will need to update this one slightly. This shouldn't require a change in version once we go to 0.5.0-dev.

**Comment by davidslater** [comment]
Moving to branch rebased off of new Dockerfile setup.

**Pull request closed without merging**
