### PR TITLE
jupyter widgets and tests

### PR DESCRIPTION
**Pull request by davidslater**
Fixes https://github.com/twosixlabs/armory/issues/1263 and adds manual tests and test data for jupyter.

### CODE REVIEW

**Comment by davidslater** [comment]
You’ll need to rebuild base to test:
```
bash docker/build-base.sh 
python docker/build.py pytorch --no-pull
armory launch pytorch --jupyter
# connect to jupyter lab and run tests in tests/test_jupyter
```

**Comment by mwartell** [comment]
Because it alters Dockerfile-base, this PR requires a rebuild and push of the `twosixarmory/base` docker image.

I just wanted to call this out explicitly in case it wasn't intended. Publishing anew is not hard, but I do believe we are hoping to update base infrequently. Of course [practicality beats purity](https://peps.python.org/pep-0020/#:~:text=Although%20practicality%20beats%20purity.).

**Comment by davidslater** [comment]
Yes, wanted to do that instead of modifying all of the derivative ones. I was hoping to get a bunch of base changes in prior to `0.15.0` release, and then get a bit more constant after that.

**Comment by davidslater** [comment]
@mwartell I think it's good for re-review. The only other addition is that I noticed an issue with jupyter prompt when using `armory launch`, so I've fixed that.

**Review by mwartell — APPROVED** [review]
LGTM

**Pull request merged**
