### PR TITLE
Utilize docker build kit

### PR DESCRIPTION
**Pull request by seanpmorgan**
Testing to see if we see a performance improvement on test cases

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Shaves a minute or two off each pytest job

**Comment by davidslater** [comment]
Nice! How does the buildkit work?

**Comment by davidslater** [comment]
Once we get all of the datasets cached, that should also cut off a lot of time.

**Comment by seanpmorgan** [comment]
> Nice! How does the buildkit work?

It's an upgraded toolkit for docker builds. Has support for remote caching, amongst other things. Also resolves the build to see what can be built in parallel.

https://github.com/moby/buildkit
https://docs.docker.com/develop/develop-images/build_enhancements/

**Pull request merged**
