### PR TITLE
more informative output path info

### PR DESCRIPTION
**Pull request by davidslater**

### CODE REVIEW

**Comment by davidslater** [comment]
This adds a final output line like:
```
2022-03-23 14:28:16 11s INFO     armory.eval.evaluator:_cleanup:133 results output written to:
/Users/david.slater/.armory/outputs/2022-03-23T212807.240833/
```
or 
```
2022-03-23 14:23:45 11s INFO     armory.eval.evaluator:_cleanup:132 results output written to:
/Users/david.slater/.armory/outputs/2022-03-23T212334.978538/ImageClassificationTask_1648070623.json
```
This precludes the need of translating from the in-container path.

**Comment by lcadalzo** [comment]
I think this doesn't smoothly handle the case where an error occurs in the scenario _before_ `self.output_dir` is created. In this case, the `except OSError` block is reached (bc `FileNotFoundError` is a subclass of it), and the line below fails in an unintended manner:

```
jsons = [x for x in os.listdir(self.output_dir) if x.endswith(".json")]
```

I think the fix would be to add an additional `except FileNotFoundError` block before the `except OSError` block. Note that it has to come before, or else the `OSError` block is reached. Like follows:

```
 except FileNotFoundError:
            pass
 except OSError:
            jsons = [x for x in os.listdir(self.output_dir) if x.endswith(".json")]
            if len(jsons) == 1:
                json = jsons[0]
            else:
                json = ""
            output_path = os.path.join(self.output_dir, json)
            log.info(f"results output written to:\n{output_path}")
```

For context, with the current state of this PR, this is what happens when the scenario errors before `self.output_dir` is created. To replicate, just run a scenario using an older Docker image:

```
2022-03-24 15:24:42  3s INFO     armory.eval.evaluator:_run_config:263 Running evaluation script
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/runpy.py", line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/opt/conda/lib/python3.7/runpy.py", line 109, in _get_module_details
__import__(pkg_name)
File "/workspace/armory/__init__.py", line 25, in <module>
from armory.logs import log
File "/workspace/armory/logs.py", line 25, in <module>
import loguru
ModuleNotFoundError: No module named 'loguru'
2022-03-24 15:24:42  3s ERROR    armory.docker.management:exec_cmd:100 command python -m armory.scenarios.main eyJfZGVzY3JpcHRpb24iOiAiQmFzZWxpbmUgRGVlcFNwZWVjaCBBU1Igb24gTGlicmlTcGVlY2gsIGNvbnRyaWJ1dGVkIGJ5IE1JVFJFIENvcnBvcmF0aW9uIiwgImFkaG9jIjogeyJza2lwX2FkdmVyc2FyaWFsIjogZmFsc2V9LCAiYXR0YWNrIjogeyJrbm93bGVkZ2UiOiAid2hpdGUiLCAia3dhcmdzIjogeyJwYXJ0aWFsX2F0dGFjayI6IGZhbHNlLCAic25yX2RiIjogMjAsICJ0YXJnZXRlZCI6IGZhbHNlfSwgIm1vZHVsZSI6ICJhcm1vcnkuYXJ0X2V4cGVyaW1lbnRhbC5hdHRhY2tzLmtlbmFuc3ZpbGxlX2RmdCIsICJuYW1lIjogIktlbmFuc3ZpbGxlREZUIiwgInVzZV9sYWJlbCI6IGZhbHNlfSwgImRhdGFzZXQiOiB7ImJhdGNoX3NpemUiOiA4LCAiZXZhbF9zcGxpdCI6ICJ0ZXN0X2NsZWFuIiwgImZyYW1ld29yayI6ICJudW1weSIsICJtb2R1bGUiOiAiYXJtb3J5LmRhdGEuZGF0YXNldHMiLCAibmFtZSI6ICJsaWJyaXNwZWVjaCIsICJ0cmFpbl9zcGxpdCI6ICJ0cmFpbl9jbGVhbjEwMCJ9LCAiZGVmZW5zZSI6IG51bGwsICJtZXRyaWMiOiB7Im1lYW5zIjogZmFsc2UsICJwZXJ0dXJiYXRpb24iOiAic25yX2RiIiwgInJlY29yZF9tZXRyaWNfcGVyX3NhbXBsZSI6IHRydWUsICJ0YXNrIjogWyJ3b3JkX2Vycm9yX3JhdGUiXX0sICJtb2RlbCI6IHsiZml0IjogZmFsc2UsICJmaXRfa3dhcmdzIjogeyJuYl9lcG9jaHMiOiAyMDAwMH0sICJtb2RlbF9rd2FyZ3MiOiB7fSwgIm1vZHVsZSI6ICJhcm1vcnkuYmFzZWxpbmVfbW9kZWxzLnB5dG9yY2guZGVlcF9zcGVlY2giLCAibmFtZSI6ICJnZXRfYXJ0X21vZGVsIiwgInByZWRpY3Rfa3dhcmdzIjogeyJ0cmFuc2NyaXB0aW9uX291dHB1dCI6IHRydWV9LCAid2VpZ2h0c19maWxlIjogbnVsbCwgIndyYXBwZXJfa3dhcmdzIjogeyJwcmV0cmFpbmVkX21vZGVsIjogImxpYnJpc3BlZWNoIn19LCAic2NlbmFyaW8iOiB7Imt3YXJncyI6IHt9LCAibW9kdWxlIjogImFybW9yeS5zY2VuYXJpb3MuYXVkaW9fYXNyIiwgIm5hbWUiOiAiQXV0b21hdGljU3BlZWNoUmVjb2duaXRpb24ifSwgInN5c2NvbmZpZyI6IHsiZG9ja2VyX2ltYWdlIjogInR3b3NpeGFybW9yeS9weXRvcmNoLWRlZXBzcGVlY2giLCAiZXh0ZXJuYWxfZ2l0aHViX3JlcG8iOiAiU2Vhbk5hcmVuL2RlZXBzcGVlY2gucHl0b3JjaEBWMy4wIiwgImdwdXMiOiAiYWxsIiwgImxvY2FsX3JlcG9fcGF0aCI6IG51bGwsICJvdXRwdXRfZGlyIjogbnVsbCwgIm91dHB1dF9maWxlbmFtZSI6IG51bGwsICJ1c2VfZ3B1IjogZmFsc2UsICJmaWxlcGF0aCI6ICJzY2VuYXJpb19jb25maWdzL2xpYnJpc3BlZWNoX2Fzcl9rZW5hbnN2aWxsZV91bmRlZmVuZGVkLmpzb24iLCAiY2hlY2siOiB0cnVlLCAibnVtX2V2YWxfYmF0Y2hlcyI6IDF9LCAiZXZhbF9pZCI6ICIyMDIyLTAzLTI0VDE5MjQ0Mi40OTkwMzIifQ== --check --num-eval-batches 1 --base64 did not finish cleanly
2022-03-24 15:24:42  3s INFO     armory.docker.management:stop_armory_instance:129 Stopping instance: 13ee400f39
2022-03-24 15:24:42  3s INFO     armory.eval.evaluator:_cleanup:116 deleting tmp_dir /home/lucas/.armory/tmp/2022-03-24T192442.499032
Traceback (most recent call last):
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/eval/evaluator.py", line 124, in _cleanup
    os.rmdir(self.output_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lucas/.armory/outputs/2022-03-24T192442.499032'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/miniconda3/envs/armory-duo-37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lucas/miniconda3/envs/armory-duo-37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/__main__.py", line 767, in <module>
    main()
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/__main__.py", line 763, in main
    func(sys.argv[2:], prog, description)
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/__main__.py", line 391, in run
    validate_config=args.validate_config,
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/eval/evaluator.py", line 245, in run
    self._cleanup()
  File "/home/lucas/Desktop/gard/git/twosixlabs/armory/armory/eval/evaluator.py", line 127, in _cleanup
    jsons = [x for x in os.listdir(self.output_dir) if x.endswith(".json")]
FileNotFoundError: [Errno 2] No such file or directory: '/home/lucas/.armory/outputs/2022-03-24T192442.499032'
```

**Comment by davidslater** [comment]
@lcadalzo pushed an update with FileNotFound and a warning message

**Review by lcadalzo — APPROVED** [review]
LGTM

**Pull request merged**
