### PR TITLE
Adding a ResNet-18 model optimized with SGD.

### PR DESCRIPTION
**Pull request by TS-Lee**
We see some attacks perform differently on a model trained on different optimizers. To test that, I want to add a ResNet-18 model optimized with SGD.

### CODE REVIEW

**Comment by TS-Lee** [comment]
Yes. We want to see if an attack or a defense is sensitive to a certain parameter, and hence it becomes inapplicable to a certain model.

**Comment by swsuggs** [comment]
Would you please run `black armory/baseline_models/pytorch/resnet18.py`, making sure you have black version 22.3.0?

**Comment by TS-Lee** [comment]
Done. It looks like it passed all tests.

**Comment by swsuggs** [comment]
Great, thanks!

**Pull request merged**
