### PR TITLE
Librispeech

### PR DESCRIPTION
**Pull request by ng390**
Closes Issue #222. Needs to be rebased -- was working on a stale version of master.

### CODE REVIEW

**Comment by davidslater** [comment]
@ng390 If you could rebase off of master, and see if the current docker containers work there, that would be great (and resolve your merge conflict).

**Comment by davidslater** [comment]
It appears to hang after the download completes:
```
>>> datasets.librispeech_speakerid("test", 1, 1, paths.docker().dataset_dir, None)
Downloading and preparing dataset librispeech_split (?? GiB) to /armory/datasets/librispeech_split/plain_text/1.1.0...
Dl Completed...:   0%|                           /opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)0 file [00:00, ? file/s]
/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:06<00:00, 13.87s/ url]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:06<00:00, 22.32s/ file]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:06<00:00, 26.07s/ file]
Dl Size...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321/321 [01:06<00:00,  4.79 MiB/s]

Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:06<00:00, 22.32s/ url]






```

**Comment by davidslater** [comment]
My fan is still going, so I'm guessing that it's doing something. How long did you have to wait to construct the dataset, @ng390 ?

**Comment by ng390** [comment]
It took about 15 minutes on my laptop.

**Comment by ng390** [comment]
The CI tests are giving errors related to not being able to locate ffprobe. ffmpeg is conda installed on the Docker container and also in test_requirements.txt, so need to dig into why this error is still being generated.

**Comment by davidslater** [comment]
@seanpmorgan are we sure that the tests use the docker container on pytest? We build it, but we don't launch it. Perhaps we need a `docker run ...` command prior to installing test-requirements and running pytest?

**Pull request merged**
