### PR TITLE
fix sleeper agent paths

### LINKED ISSUE #1659: Poisoning Trigger Paths in Configs
Currently, these point to paths in armory, but assume that the working directory is project root.

https://github.com/twosixlabs/armory/blob/develop/scenario_configs/eval6/poisoning/audio_backdoor_undefended.json#L19

These should be made less brittle, e.g., by using the package structure.

### LINKED ISSUE #1690: Update poisoning.md
Mention sleeper agent and audio poisoning.  Possibly de-emphasize Witches' Brew as it is unlikely to be used again.

### PR DESCRIPTION
**Pull request by davidslater**
Fixes #1690
Fixes #1659
(For the latter, I discovered a case that wasn't previously fixed.)

### CODE REVIEW

**Comment by davidslater** [comment]
To test, you'll need to build a new `pytorch` docker image.

**Comment by davidslater** [comment]
Try with:
```twosixlabs/armory/scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p01_undefended.json```

The `p00` version doesn't poison, I don't think.

I would change `train_epochs` to 1 in the `adhoc` config and use `--check`.

``2022-10-27 17:15:10  8s INFO     art.estimators.classification.pytorch:get_layers:1159 Inferred 1 hidden layers on PyTorch classifier.                                               
2022-10-27 17:15:10  8s INFO     armory.scenarios.poisoning_sleeper_agent:load_poisoner:77 Fitting proxy model for attack . . .                                                      
2022-10-27 17:15:19 17s ERROR    armory.scenarios.scenario:evaluate:399 Encountered error during scenario evaluation.                                                                
Traceback (most recent call last):                                                                                                                                                   
File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                                           
return _run_code(code, main_globals, None,                                                                                                                                           
│         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...                                   
│         └ <code object <module> at 0x7f2968070d40, file "/armory-repo/armory/scenarios/main.py", line 1>                                                                           
└ <function _run_code at 0x7f2a486b89d0>                                                                                                                                             
File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code                                                                                                                      exec(code, run_globals)                                                                                                                                                              
│     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...                                             
└ <code object <module> at 0x7f2968070d40, file "/armory-repo/armory/scenarios/main.py", line 1>                                                                                     
File "/armory-repo/armory/scenarios/main.py", line 228, in <module>                                                                                                                  
run_config(                                                                                                                                                                          
└ <function run_config at 0x7f2962edcd30>                                                                                                                                            
File "/armory-repo/armory/scenarios/main.py", line 144, in run_config                                                                                                                
scenario.evaluate()                                                                                                                                                                  
│        └ <function Scenario.evaluate at 0x7f2962ba71f0>                                                                                                                            
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7f2a4856d760>                                                                                           
> File "/armory-repo/armory/scenarios/scenario.py", line 390, in evaluate                                                                                                            
self._evaluate()                                                                                                                                                                     
│    └ <function Scenario._evaluate at 0x7f2962ba7160>                                                                                                                               
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7f2a4856d760>                                                                                           
File "/armory-repo/armory/scenarios/scenario.py", line 379, in _evaluate                                                                                                             
self.load()                                                                                                                                                                          
│    └ <function Poison.load at 0x7f2962bab040>                                                                                                                                      
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7f2a4856d760> 
File "/armory-repo/armory/scenarios/poison.py", line 453, in load                         
self.load_poisoner()                                                                      
│    └ <function SleeperAgentScenario.load_poisoner at 0x7f2962bab790>
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7f2a4856d760> 
File "/armory-repo/armory/scenarios/poisoning_sleeper_agent.py", line 109, in load_poisoner
patch = Image.open(
        │     └ <function open at 0x7f297512c9d0>
        └ <module 'PIL.Image' from '/opt/conda/lib/python3.9/site-packages/PIL/Image.py'>
File "/opt/conda/lib/python3.9/site-packages/PIL/Image.py", line 2975, in open
fp = builtins.open(filename, "rb")
│        │    └ 'armory/utils/triggers/trigger_10.png'
│        └ <built-in function open>
└ <module 'builtins' (built-in)>
FileNotFoundError: [Errno 2] No such file or directory: 'armory/utils/triggers/trigger_10.png'
```

**Comment by lcadalzo** [comment]
I was able to reproduce the error and then confirm the error went away with the updates on this branch. Per our discussion earlier, a different error came up, which I'll post a Traceback for. I'll wait to merge until the fix for this error is added

```
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
│         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
│         └ <code object <module> at 0x7ff344b11c90, file "/armory-repo/armory/scenarios/main.py", line 1>
└ <function _run_code at 0x7ff421bd39d0>
File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
│     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
└ <code object <module> at 0x7ff344b11c90, file "/armory-repo/armory/scenarios/main.py", line 1>
File "/armory-repo/armory/scenarios/main.py", line 228, in <module>
run_config(
└ <function run_config at 0x7ff343985d30>
File "/armory-repo/armory/scenarios/main.py", line 144, in run_config
scenario.evaluate()
│        └ <function Scenario.evaluate at 0x7ff3436481f0>
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7ff421a687c0>
> File "/armory-repo/armory/scenarios/scenario.py", line 391, in evaluate
self._evaluate()
│    └ <function Scenario._evaluate at 0x7ff343648160>
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7ff421a687c0>
File "/armory-repo/armory/scenarios/scenario.py", line 380, in _evaluate
self.load()
│    └ <function Poison.load at 0x7ff34364b0d0>
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7ff421a687c0>
File "/armory-repo/armory/scenarios/poison.py", line 455, in load
self.poison_dataset()
│    └ <function SleeperAgentScenario.poison_dataset at 0x7ff34364b940>
└ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7ff421a687c0>
File "/armory-repo/armory/scenarios/poisoning_sleeper_agent.py", line 142, in poison_dataset
) = self.poisoner.poison_dataset(
    │    │        └ <function DatasetPoisonerSleeperAgent.poison_dataset at 0x7ff34364b820>
    │    └ <armory.scenarios.poisoning_sleeper_agent.DatasetPoisonerSleeperAgent object at 0x7ff2bf5e6dc0>
    └ <armory.scenarios.poisoning_sleeper_agent.SleeperAgentScenario object at 0x7ff421a687c0>
File "/armory-repo/armory/scenarios/poisoning_sleeper_agent.py", line 50, in poison_dataset
x_poison, y_poison = self.attack.poison(
                     │    │      └ <function SleeperAgentAttack.poison at 0x7ff2bf583a60>
                     │    └ <art.attacks.poisoning.sleeper_agent_attack.SleeperAgentAttack object at 0x7ff33c34b0a0>
                     └ <armory.scenarios.poisoning_sleepe
r_agent.DatasetPoisonerSleeperAgent object at 0x7ff2bf5e6dc0>
File "/opt/conda/lib/python3.9/site-packages/art/attacks/poisoning/sleeper_agent_attack.py", line 206, in poison
self.indices_poison = self._select_poison_indices(
│                     │    └ <function SleeperAgentAttack._select_poison_indices at 0x7ff2bf583d30>
│                     └ <art.attacks.poisoning.sleeper_agent_attack.SleeperAgentAttack object at 0x7ff33c34b0a0>
└ <art.attacks.poisoning.sleeper_agent_attack.SleeperAgentAttack object at 0x7ff33c34b0a0>
File "/opt/conda/lib/python3.9/site-packages/art/attacks/poisoning/sleeper_agent_attack.py", line 397, in _select_poison_indices
image = torch.tensor(x, dtype=torch.float32).float().to(device)
│     │      │        │     │                   └ device(type='cuda')
│     │      │        │     └ torch.float32
│     │      │        └ <module 'torch' from '/opt/conda/lib/python3.9/site-packages/torch/__init__.py'>
│     │      └ array([[[0.27058825, 0.28235295, 0.24313726],
│     │                [0.25882354, 0.27058825, 0.23921569],
│     │                [0.25490198, 0.26666668, ...
│     └ <built-in method tensor of type object at 0x7ff3eb80c200>
└ <module 'torch' from '/opt/conda/lib/python3.9/site-packages/torch/__init__.py'>
File "/opt/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
torch._C._cuda_init()
│     │  └ <built-in function _cuda_init>
│     └ <module 'torch._C' from '/opt/conda/lib/python3.9/site-packages/torch/_C.cpython-39-x86_64-linux-gnu.so'>
└ <module 'torch' from '/opt/conda/lib/python3.9/site-packages/torch/__init__.py'>
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```

**Comment by davidslater** [comment]
@lcadalzo that should have fixed the device use problem

**Comment by lcadalzo** [comment]
Confirmed that the update fixes the device use problem

**Comment by lcadalzo** [comment]
LGMT, unless we want to manually trigger the CI from your fork, since it's not automatically triggered by a merge into `rc0.16.1`

**Comment by ani0075saha** [comment]
@lcadalzo @davidslater 

I am seeing this issue when I try scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p50_undefended_debug.json
```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
The docker image being used is twosixarmory/armory:0.19.2
and
``` 
armory-testbed            0.19.2                   pypi_0    pypi
```

Any suggestions as to how to solve this?

EDIT:
It seems CUDA is not available inside the container. I tried running the container in interactive mode. 
I don't have any issues using the GPU outside the container.
```
I have no name!@98dc986acdd3:/workspace$ python -c "import torch; print(torch.zeros(1).cuda()); print(torch.cuda.is_available())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by swsuggs** [comment]
@ani0075saha 
Do you have an NVIDIA driver on your machine?  Check this [response](https://github.com/Deep-MI/FastSurfer/issues/39#issuecomment-735691972) for more info.

My other guess is that you may need to install and/or configure the nvidia-container-toolkit.
If you ```cat /etc/docker/daemon.json``` or locate Runtimes in the output of ```docker info```, you should see a runtime for ```nvidia```.  If you don't see it, try following the [directions here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

**Pull request merged**
