### PR TITLE
Imagenette dataset added, included in download_all_data

### PR DESCRIPTION
**Pull request by ng390**
Imagenette dataset added, included in download_all_data. Note that this requires an update to the docker images as it introduces a dependency to Pillow.

### CODE REVIEW

**Comment by ng390** [comment]
Note that the CI tests will fail because the CI script will pull an older docker image without Pillow. Blocked from passing CI tests until the new Docker image is published.

**Comment by davidslater** [comment]
@ng390 Can you rebase off of master? We updated the docker container to 0.4.0, and that includes Pillow, so this should simplify your merge.

**Comment by ng390** [comment]
The Imagenette dataset is too big to fit in memory on the CI virtual machine. Once dataset generators are incorporated will be able to CI test. (Issue #104)

**Comment by davidslater** [comment]
Please rebase off of master - should fix a number of merge issues.

**Comment by davidslater** [comment]
Use TFDS ImageNette instead.

**Pull request closed without merging**
