### PR TITLE
updating VideoTrackingExporter class for new label format

### LINKED ISSUE #1824: Error when using export_samples for carla_mot scenario
This appears to result because `y` is a list of length `total # of boxes in the video` in the format of `List[dict]` where each `dict` has the standard [coco keys](https://cocodataset.org/#format-data). Meanwhile, `get_sample()` is expecting `y` to be a dict with integer keys for each frame index

```
  File "/workspace/armory/instrument/export.py", line 644, in measure
    self.exporter.export(
    │    │        └ <function SampleExporter.export at 0x7f76823188b0>
    │    └ <armory.instrument.export.VideoTrackingExporter object at 0x7f767e65d6d0>
    └ <armory.instrument.export.ExportMeter object at 0x7f767e65d700>

  File "/workspace/armory/instrument/export.py", line 30, in export
    self._export(
    │    └ <function VideoTrackingExporter._export at 0x7f768232e1f0>
    └ <armory.instrument.export.VideoTrackingExporter object at 0x7f767e65d6d0>

  File "/workspace/armory/instrument/export.py", line 375, in _export
    self.frames_with_boxes = self.get_sample(
    │                        │    └ <function VideoTrackingExporter.get_sample at 0x7f768232e280>
    │                        └ <armory.instrument.export.VideoTrackingExporter object at 0x7f767e65d6d0>
    └ <armory.instrument.export.VideoTrackingExporter object at 0x7f767e65d6d0>

  File "/workspace/armory/instrument/export.py", line 418, in get_sample
    bboxes_true = y["boxes"][n_frame].astype("float32")
                  │          └ 0
                  └ [{'image_id': 0, 'category_id': 1, 'bbox': [195.0, 253.0, 28.0, 33.0], 'score': 1.0, 'object_id': 1001, 'visibility': 1.0}, {...

TypeError: list indices must be integers or slices, not str

```

To reproduce, run `armory run scenario_configs/eval6/carla_mot/carla_mot_dpatch_defended.json` after modifying the JSON to set `export_batches: true` (use --skip-attack and --num-eval-batches 1 to yield the error faster)

### PR DESCRIPTION
**Pull request by lcadalzo**
Closes #1824, see link for description of the bug and how to reproduce

### CODE REVIEW

**Comment by jprokos26** [comment]
I can't seem to replicate this issue on [dbe6ce4c8225130a2a12e6fa5b71c4f8bb438fad](https://github.com/twosixlabs/armory/tree/dbe6ce4c8225130a2a12e6fa5b71c4f8bb438fad). Ran using the following:
`python -m armory run scenario_configs/eval5/carla_video_tracking/carla_video_tracking_goturn_advtextures_defended.json --check` and generated the output images without any errors.

**Comment by lcadalzo** [comment]
@jprokos26 the error was observed using `scenario_configs/eval6/carla_mot/carla_mot_dpatch_defended.json`

**Comment by jprokos26** [comment]
I have been able to reproduce the error on develop and running with the proposed change behaves as expected.

**Review by jprokos26 — APPROVED** [review]

**Comment by lcadalzo** [comment]
@jprokos26 please merge and close the issue if you're finished reviewing and have no requested changes

**Pull request merged**
