### PR TITLE
replace a line incorrectly removed

### PR DESCRIPTION
**Pull request by mwartell**
I failed to notice this CI variable was needed when I reviewed pull #1323. I'm putting it back.

### CODE REVIEW

**Review by davidslater — CHANGES_REQUESTED** [review]
Looks like the end2end test is still failing. Maybe add an echo of the imageTag at the end of the first stage to confirm the version?

I had previously run into problems (before this line was removed) where `python setup.py --version` was outputting a 0.1.g98a7a... version. There was also a warning about the clone being "shallow", indicating that the the checkout action did not retrieve the full git history. I think what was happening there is that the git history didn't go far enough back to find a version tag, and therefore it defaulted to a version 0, incremented to 0.1 with a hash tag.

**Comment by davidslater** [comment]
It looks like the environment variable imageTag is set properly in the first stage, but somehow it's not propagating to the later stages.

**Comment by davidslater** [comment]
@mwartell I think there's an additional line we need to add back:
https://github.com/shenshaw26/armory/blob/duo/.github/workflows/end2end_cron.yml#L34-L36

It looks like this line does more than echo:
```
echo "::set-output name=imageTag::$imageTag"
```

**Comment by davidslater** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions

**Comment by davidslater** [comment]
Testing...

**Comment by davidslater** [comment]
@shenshaw26 did these end2end tests ever work on github? I think that the built docker containers would not survive for the subsequent tests (unless they got pushed to dockerhub or somewhere else). These could work if they were put into the same test, though that would seem like a rather long test.

**Comment by shenshaw26** [comment]
The end-to-end tests were put together to run on the self hosted runner, the last time I messed with them, however it now appears that they are trying to run in the github runner.  @mwartell, is that change intentional?  I thought we had setup the local runner on AWS to do the end-to-end tests (I realize that we did that on our own fork, but I assumed we would migrate that bit over as well)

**Comment by davidslater** [comment]
@mwartell is this update pertinent to your current PR work, or can it be closed?

**Comment by mwartell** [comment]
Fixed by WIP #1422. Transmitting values between steps in actions is dodgy; I cured the problem by having each step get the tag itself.

**Pull request closed without merging**
