### PR TITLE
add global meter

### PR DESCRIPTION
**Pull request by davidslater**
This functionality should make it easier and less error prone to use global (population-wise) metrics.

Partially addresses #1447

Still to do:
- [x] Add test for global meter
- [x] Update docs
- [x] Update scenarios to match use

### CODE REVIEW

**Comment by davidslater** [comment]
Will need to wait until the task metric PR is merged to really test.

**Comment by swsuggs** [comment]
GlobalMeter should be included in instrument/__init__.py

**Comment by swsuggs** [comment]
I get an error when I run the tests:
```
>           scenario_probe.update(y_pred=y_pred)

tests/unit/test_instrument.py:774: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
armory/instrument/instrument.py:117: in update
    self.sink.update(name, value)
armory/instrument/instrument.py:357: in update
    meter.set(arg, value, self.context["batch"])
armory/instrument/instrument.py:549: in set
    self.measure()
armory/instrument/instrument.py:570: in measure
    result = self.metric(*self.values, **self.metric_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x_batch = 9
x_adv_batch = array([14.20650527, 13.98658567, 13.29061285, 13.14462465, 12.11244463,
       12.90315492, 13.65862198, 12.65089432, 13.25145121, 13.56685269])
kwargs = {}

    @functools.wraps(element_metric)
    def wrapper(x_batch, x_adv_batch, **kwargs):
>       x_batch = list(x_batch)
E       TypeError: 'int' object is not iterable

armory/metrics/common.py:71: TypeError

```

**Comment by davidslater** [comment]
Added init

**Comment by davidslater** [comment]
Test failure seems unrelated to this PR. That said, fixed.

**Review by swsuggs — APPROVED** [review]
looks good to me

**Pull request merged**
