### PR TITLE
For Issue #1370 - Updated CARLA object detection dev dataset

### PR DESCRIPTION
**Pull request by yusong-tan**
Dataset link to be sent separately

### CODE REVIEW

**Comment by yusong-tan** [comment]
Against this dataset, I get the following results using Adversarial Patch attack.

```
{
    "armory_version": "0.14.5.g4de82f0",
    "config": {
        "_description": "CARLA single modality object detection, contributed by MITRE Corporation",
        "adhoc": null,
        "attack": {
            "knowledge": "white",
            "kwargs": {
                "batch_size": 1,
                "learning_rate": 0.01,
                "max_iter": 1000,
                "optimizer": "pgd",
                "targeted": false,
                "verbose": true
            },
            "module": "armory.art_experimental.attacks.carla_obj_det_adversarial_patch",
            "name": "CARLAAdversarialPatchPyTorch",
            "use_label": true
        },
        "dataset": {
            "batch_size": 1,
            "eval_split": "dev",
            "framework": "numpy",
            "modality": "rgb",
            "module": "armory.data.adversarial_datasets",
            "name": "carla_obj_det_dev"
        },
        "defense": null,
        "eval_id": "2022-04-28T024214.366284",
        "metric": {
            "means": true,
            "perturbation": "l0",
            "record_metric_per_sample": false,
            "task": [
                "carla_od_AP_per_class",
                "carla_od_disappearance_rate",
                "carla_od_hallucinations_per_image",
                "carla_od_misclassification_rate",
                "carla_od_true_positive_rate"
            ]
        },
        "model": {
            "fit": false,
            "fit_kwargs": {},
            "model_kwargs": {
                "num_classes": 4
            },
            "module": "armory.baseline_models.pytorch.carla_single_modality_object_detection_frcnn",
            "name": "get_art_model",
            "weights_file": "carla_rgb_weights_eval5.pt",
            "wrapper_kwargs": {}
        },
        "scenario": {
            "export_batches": true,
            "kwargs": {
                "check_run": false,
                "num_eval_batches": null,
                "skip_attack": false,
                "skip_benign": false,
                "skip_misclassified": false
            },
            "module": "armory.scenarios.carla_object_detection",
            "name": "CarlaObjectDetectionTask"
        },
        "sysconfig": {
            "docker_image": "twosixarmory/pytorch:0.14.5.gec35a62",
            "external_github_repo": null,
            "filepath": "scenario_configs/carla_obj_det_adversarialpatch_undefended.json",
            "gpus": "1",
            "output_dir": null,
            "output_filename": "carla_obj_det_adversarialpatch_undefende",
            "use_gpu": true
        }
    },
    "results": {
        "adversarial_carla_od_AP_per_class": {
            "1": 0.47,
            "2": 0.39,
            "3": 0.68
        },
        "adversarial_carla_od_AP_per_class_wrt_benign_preds": {
            "1": 0.5,
            "2": 0.33,
            "3": 0.72
        },
        "adversarial_mean_carla_od_AP_per_class": 0.5133333333333333,
        "adversarial_mean_carla_od_AP_per_class_wrt_benign_preds": 0.5166666666666667,
        "adversarial_mean_carla_od_disappearance_rate": 0.3164788093932381,
        "adversarial_mean_carla_od_disappearance_rate_wrt_benign_preds": 0.681186261316959,
        "adversarial_mean_carla_od_hallucinations_per_image": 24.096774193548388,
        "adversarial_mean_carla_od_hallucinations_per_image_wrt_benign_preds": 19.967741935483872,
        "adversarial_mean_carla_od_misclassification_rate": 0.0547499626147384,
        "adversarial_mean_carla_od_misclassification_rate_wrt_benign_preds": 0.05245955481621396,
        "adversarial_mean_carla_od_true_positive_rate": 0.6287712279920235,
        "adversarial_mean_carla_od_true_positive_rate_wrt_benign_preds": 0.266354183866827,
        "benign_carla_od_AP_per_class": {
            "1": 0.72,
            "2": 0.67,
            "3": 0.9
        },
        "benign_mean_carla_od_AP_per_class": 0.7633333333333333,
        "benign_mean_carla_od_disappearance_rate": 0.19332832162924782,
        "benign_mean_carla_od_hallucinations_per_image": 3.967741935483871,
        "benign_mean_carla_od_misclassification_rate": 0.05859829311841696,
        "benign_mean_carla_od_true_positive_rate": 0.7480733852523352,
        "perturbation_mean_l0": 0.005007709243391578
    },
    "timestamp": 1651113740
}
```

**Comment by lcadalzo** [comment]
@yusong-tan this differs from what you put in the url_checksum file, so just a heads up:

```
(armory) lucas@ubu0953:~/Desktop/gard/git/twosixlabs/armory$ sha256sum ~/Downloads/carla_od_dev_2.0.0.tar.gz 
30c7593817867eb97b3c7e1358451c576805bb4423599b09ad99f15a2ebdd5c9
```

**Comment by yusong-tan** [comment]
> @yusong-tan this differs from what you put in the url_checksum file, so just a heads up:
> 
> ```
> (armory) lucas@ubu0953:~/Desktop/gard/git/twosixlabs/armory$ sha256sum ~/Downloads/carla_od_dev_2.0.0.tar.gz 
> 30c7593817867eb97b3c7e1358451c576805bb4423599b09ad99f15a2ebdd5c9
> ```

Yes, yours is correct. I'm not sure where the PR'ed checksum came from.

**Comment by lcadalzo** [comment]
Marking `WIP` until CI errors are debugged

**Comment by lcadalzo** [comment]
1.0.1:
```
>>> y[1].keys()
dict_keys(['cc_ground_truth', 'cc_scene', 'gs_coords', 'mask', 'shape'])
```

2.0.0:
```
(Pdb) y[1].keys()
dict_keys(['avg_patch_depth', 'gs_coords', 'mask'])

```

**Comment by lcadalzo** [comment]
I did confirm that 2.0.0 works with the `CARLAAdversarialPatchPyTorch` attack

**Comment by yusong-tan** [comment]
> @yusong-tan it appears that 2.0.0 removed the `"shape"` field in the patch metadata? This is causing an error when running the `CARLADapricotPatch` attack. A KeyError [here](https://github.com/yusong-tan/armory/blob/eval5_carla_obj_det_dev/armory/art_experimental/attacks/carla_obj_det_patch.py#L609)

@lcadalzo See PR #1452. With this change, I confirmed this dev dataset works with `CARLADapricotPatch` in both single modality and multimodality configs.

**Comment by davidslater** [comment]
I'm guessing that performers will want to still be able to access the old data. Will this still enable access to those?

**Comment by yusong-tan** [comment]
> I'm guessing that performers will want to still be able to access the old data. Will this still enable access to those?

Yes, if the old dataset defines `shape`, `cc_ground_truth`, and `cc_scene`, then the attack will still use them. I'm going to push another update to #1452 in a minute to make sure the color correction values are used when available.

**Comment by davidslater** [comment]
Yes, it does. When we finish the datasets update, we can make it easier to access those.

**Comment by lcadalzo** [comment]
@yusong-tan I'm able to reproduce the results you posted above. Having not been able to pore over the dataset yet, do you have thoughts as to why mAP is so much higher (both benign and adversarial)? Is this due in large part to the removal of the various tiny annotations in version 1.* of the dataset? Differences in the model training procedure?

**Comment by lcadalzo** [comment]
@swsuggs or @davidslater : can one of you try loading the dataset as well and merge if that goes ok? At this point I don't intend to make further changes

**Comment by davidslater** [comment]
@swsuggs can you handle this? I'm still working on ASR bugs.

**Pull request merged**
