### PR TITLE
bump art version to 1.6.2

### LINKED ISSUE #1083: Object detection label format not suitable for loss_gradient() calculation
See related ART [issue](https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/1119#issuecomment-848821698). ART <= 1.6.1 requires `"scores"` key (meaning the `y` fed to `loss_gradient()` needed to be predicted labels not ground-truth). This has been fixed for ART 1.6.2.

However, with the current Armory label format, calling `loss_gradient(x, ground_truth_y)` yields the error linked above. This error appears to go away when reshaping the `"label"` field from `(1, num_boxes)` to `(num_boxes,)`.

### PR DESCRIPTION
**Pull request by lcadalzo**
Bump ART version to 1.6.2. Also update OD label format for ART 1.6.2 bugfix which enables computing Faster-RCNN gradients with ground truth y. Closes #1083

### CODE REVIEW

**Comment by lcadalzo** [comment]
Seeing a `ModuleNotFoundError` for the `ffmpeg` package, at least for the `pytorch` image:

```
(gard) lucascadalzo@ubu0377:~/Desktop/gard/git/twosixlabs/armory$ python -m armory run scenario_configs/xview_frcnn.json --check
2021-06-11 17:14:13 ubu0377 armory.docker.management[21287] INFO ARMORY Instance 30919a3733 created.
2021-06-11 17:14:13 ubu0377 armory.eval.evaluator[21287] INFO Running evaluation script
2021-06-11 21:14:20.204938: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-06-11 21:14:28 30919a3733a6 __main__[6] WARNING Outputs will be written to /armory/outputs/2021-06-11T211412.695412
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/workspace/armory/scenarios/base.py", line 402, in <module>
args.skip_misclassified,
File "/workspace/armory/scenarios/base.py", line 289, in run_config
scenario = config_loading.load(scenario_config)
File "/workspace/armory/utils/config_loading.py", line 36, in load
module = import_module(sub_config["module"])
File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/workspace/armory/scenarios/object_detection.py", line 7, in <module>
from armory.scenarios.image_classification import ImageClassificationTask
File "/workspace/armory/scenarios/image_classification.py", line 23, in <module>
from armory.utils.export import SampleExporter
File "/workspace/armory/utils/export.py", line 4, in <module>
import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'
```

**Comment by mwartell** [comment]
I saw a number of missing `host-requirements.txt` packages in 0.13.x which I needed to bring in as 4e21bcdc001891612c38145387e8f08696f3f0fd. 

My guess was that these were brought in via conda on the docker builds (for example, conda pytorch might bring in pandas). I'm not sure that guess is correct now.

**Comment by ng390** [comment]
The conda version of ffmpeg is needed as a command-line tool by tensorflow-datasets 3.2; the usage of the command-line tool is buried in a subprocess.Popen [call](https://github.com/tensorflow/datasets/blob/61ce68ce6149122c121172915fe05de2332f8f4f/tensorflow_datasets/core/features/video_feature.py#L133-L136).

I took a look in older containers, e.g. the Dockerhub version of twosixarmory/pytorch:0.13.1, and the installed ffmpeg library in site-packages appears to be [ffmpeg-python](0.2.0 https://pypi.org/project/ffmpeg-python/). The library doesn't appear to be very actively developed, which may be why the library that originally pulled it in dropped it.

**Comment by lcadalzo** [comment]
[Link](https://github.com/lcadalzo/armory/actions/runs/936331109) to CI tests

**Comment by lcadalzo** [comment]
CI tests all pass. Running configs in `scenario_configs/` to test for any issues before removing the WIP

**Pull request merged**
