### PR TITLE
RESISC45 attacks in png format 

### PR DESCRIPTION
**Pull request by grobertson-ext**
.jpeg images were not attaining the accuracy we expected. Changed images to .png format and upgraded to 0.8.0-dev.

### CODE REVIEW

**Comment by grobertson-ext** [comment]
@davidslater @seanpmorgan Did you see the latest commit from last week changing the version number and returning the dataset name to the original name?

**Comment by davidslater** [comment]
Yes, I saw the latest and should have that merged soon.

**Comment by davidslater** [comment]
If checks pass, should be ready to merge.

**Comment by davidslater** [comment]
Fixes #568

**Pull request merged**
