### PR TITLE
version take 2

### PR DESCRIPTION
**Pull request by davidslater**

### CODE REVIEW

**Comment by mwartell** [comment]
There are dueling changes between this and #1634. This PR covers some of the changes suggested there, but not all. They should be reconciled **after** this is merged.

**Review by mwartell — COMMENTED** [review]
The metadata rewrite on line 106 is horrifying, but it didn't come in on this PR and will be treated in #1634

**Comment by mwartell** [comment]
Getting an error in testing:
```
armory run scenario_configs/cifar10_baseline.json --check --log=debug
/home/msw/.local/lib/python3.10/site-packages/setuptools_scm/config.py:56: UserWarning: absolute root path '/home/msw/twosix/armory' overrides relative_to '/home/msw/.local/lib/python3.10/site-packages/armory/utils/version.py'
  warnings.warn(
2022-10-05 13:10:01  0s DEBUG    armory.__main__:run:375 unifying sysconfig {'docker_image': 'twosixarmory/pytorch', 'external_github_repo': None, 'gpus': 'all', 'output_dir': None, 'output_filename': None, 'use_gpu': False} and args Namespace(filepath='scenario_configs/cifar10_baseline.json', debug=False, log_level=['debug'], interactive=False, jupyter=False, port=None, use_gpu=False, no_gpu=False, gpus=None, no_docker=False, root=False, index=None, classes=None, output_dir=None, output_filename=None, check=True, num_eval_batches=None, skip_benign=False, skip_attack=False, skip_misclassified=False, validate_config=False)
2022-10-05 13:10:01  0s INFO     armory.eval.evaluator:__init__:32 Constructing Evaluator Object
2022-10-05 13:10:01  0s INFO     armory.eval.evaluator:__init__:63 Retrieving Environment Variables
2022-10-05 13:10:01  0s INFO     armory.docker.images:ensure_image_present:155 Retrieved canonical image name for twosixarmory/pytorch as twosixarmory/pytorch:0.15.4.post265.g6b18ca55
Traceback (most recent call last):
  File "/home/msw/.local/bin/armory", line 8, in <module>
    sys.exit(main())
  File "/home/msw/.local/lib/python3.10/site-packages/armory/__main__.py", line 775, in main
    func(sys.argv[2:], prog, description)
  File "/home/msw/.local/lib/python3.10/site-packages/armory/__main__.py", line 389, in run
    rig = Evaluator(config, no_docker=args.no_docker, root=args.root)
  File "/home/msw/.local/lib/python3.10/site-packages/armory/eval/evaluator.py", line 75, in __init__
    kwargs["image_name"] = images.ensure_image_present(image_name)
  File "/home/msw/.local/lib/python3.10/site-packages/armory/docker/images.py", line 157, in ensure_image_present
    prev_release = last_armory_release(canon_image_name)
  File "/home/msw/.local/lib/python3.10/site-packages/armory/docker/images.py", line 114, in last_armory_release
    raise ValueError(
ValueError: Tag 0.15.4.post265.g6b18ca55 must be in major.minor.patch[.hash] SCM version format
```
I don't know that this is attributable to this PR yet.

**Review by mwartell — APPROVED** [review]
I've manually tested the version system in:
 1. nominal configuration
 2. missing .git repo
 3. shallow .git repo.
 
I will merge when CI completes.

**Comment by davidslater** [comment]
CI tests are weird. Thoughts?

**Comment by mwartell** [comment]
It is symptomatic of shallow clones breaking `setuptools_scm`. I'm hunting that down.

For example, https://github.com/pypa/setuptools_scm/issues/414 but we've also seen it before.

**Comment by davidslater** [comment]
I merged develop in. Hopefully checks will pass now.

**Pull request merged**
