### PR TITLE
round to nearest int when exporting, rather than rounding down

### PR DESCRIPTION
**Pull request by lcadalzo**
Addresses #1858

### CODE REVIEW

**Comment by lcadalzo** [comment]
@dxoigmn thanks for reporting this issue. If you're able to, please let us know if this PR mitigates the issue by rounding to nearest int rather than down

**Comment by dxoigmn** [comment]
I believe round to nearest integer mitigates the issue.

**Review by mwartell — APPROVED** [review]
This is a straight-forward conversion of returns `astype(int)`

**Comment by mwartell** [comment]
> @dxoigmn @lcadalzo
> 
> You need to convert to `np.uint8` instead of `int`. `PIL` will not produce the expected images if you give `int`.

I didn't account for this in my review. I've tagged myself to look at this again when this comment is considered.

**Comment by lcadalzo** [comment]
thanks @mzweilin for pointing this out. I've also now confirmed this is the case and have added a commit to address it

**Review by mwartell — APPROVED** [review]
Properly changes return types to `np.uint8` as intended.

**Pull request merged**
