### PR TITLE
Integrate ART 1.9.1 including Tensorboard feature

### PR DESCRIPTION
**Pull request by lcadalzo**
This PR does 3 things:

1. bumps Armory version to 0.14.3
2. updates Dockerfiles to A) pin to ART 1.9.1 and B) include packages needed for Tensorboard integration
3. Adds some code to generic scenario class that directs all TF event files (used by Tensorboard, outputted by ART) to the Armory output dir. This overrides ART's approach which is the following, assuming the `summary_writer` kwarg is provided: if the value for the `summary_writer` kwarg is `true`, it outputs to the current working directory; if the value is a string, it outputs to that user-specified directory. To reiterate, with this PR, Armory will force all TF event files to the Armory output dir e.g. `~/.armory/outputs/2022-01-06T224911.011884`. It does provide a warning if the user provides a string for `summary_writer`.

To test the Tensorboard integration, add `"summary_writer": true` as an attack kwarg. Note that this is only supported for certain attacks, e.g. PGD. Then, after running the scenario, run the following command: `tensorboard --logdir <ARMORY SCENARIO OUTPUT DIR>`. Note that you'll need to install tensorboard first. After running the command, follow the instructions logged to view the plots

### CODE REVIEW

**Comment by lcadalzo** [comment]
Link to CI tests: https://github.com/lcadalzo/armory/actions/runs/1641704630

**Comment by lcadalzo** [comment]
The Tensorboard feature appears to work with a PyTorch model (and Docker image), but I'm seeing the following error when I try with a KerasClassifier inside a TF1 Docker image:

```
Traceback (most recent call last):
  File "/workspace/armory/scenarios/scenario.py", line 354, in evaluate
    results = self._evaluate()
  File "/workspace/armory/scenarios/scenario.py", line 345, in _evaluate
    self.evaluate_all()
  File "/workspace/armory/scenarios/scenario.py", line 260, in evaluate_all
    self.evaluate_current()
  File "/workspace/armory/scenarios/scenario.py", line 330, in evaluate_current
    self.run_attack()
  File "/workspace/armory/scenarios/scenario.py", line 305, in run_attack
    x_adv = self.attack.generate(x=x, y=y_target, **self.generate_kwargs)
  File "/tmp/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py", line 194, in generate
    return self._attack.generate(x=x, y=y, **kwargs)
  File "/tmp/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py", line 355, in generate
    self._batch_id,
  File "/tmp/.local/lib/python3.7/site-packages/art/attacks/evasion/fast_gradient.py", line 524, in _compute
    perturbation = self._compute_perturbation(batch, batch_labels, mask_batch)
  File "/tmp/.local/lib/python3.7/site-packages/art/attacks/evasion/fast_gradient.py", line 399, in _compute_perturbation
    targeted=self.targeted,
  File "/tmp/.local/lib/python3.7/site-packages/art/summary_writer.py", line 211, in update
    loss = estimator.compute_loss(x=x, y=y)
  File "/tmp/.local/lib/python3.7/site-packages/art/estimators/classification/keras.py", line 404, in compute_loss
    loss_function.reduction = self._losses.Reduction.NONE
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow.python.keras.api._v1.keras.losses' has no attribute 'Reduction'

```

I had notified the ART team of this and heard it was supposed to be fixed, but I'm still seeing the error.

**Comment by lcadalzo** [comment]
The error above is addressed in ART's `development_issue_1465` branch, which is to be merged into `dev_1.9.1`, which will become ART `1.9.1`. So once ART `1.9.1` is released, we can pin Armory to that and we should be all set.

**Review by swsuggs — APPROVED** [review]
I tested tf and pytorch configs with success

**Pull request merged**
