### PR TITLE
adding databuilder for the test data for carla single and multi-modal…

### PR DESCRIPTION
**Pull request by yusong-tan**
…ity object detection scenarios

Test dataset will be sent separately via email.

### CODE REVIEW

**Comment by lcadalzo** [comment]
Are there supposed to `"small"`, `"large"`, and `"medium"` splits or is this accidentally copied code from DAPRICOT? If yes, what do these indicate and why do they exist for `"test"` but not `"dev"`set?

**Comment by yusong-tan** [comment]
@lcadalzo Yes, those splits are supposed to be there, just as a way to explicitly understand better if there are differences in defenses under different patch sizes. Small is <= 0.5% patch ratio, medium is between 0.5% and 0.75%, and large is between 0.75% and 1% (one or two patch may be slightly larger than 1%). These splits were added after 'dev' dataset was developed. A good defense should generalize to different patch sizes, so 'dev' lacking such explicit splits shouldn't be a hindrance to research.

**Comment by lcadalzo** [comment]
Got it. And to clarify dataset size: I should be seeing 10 examples per split?

**Comment by yusong-tan** [comment]
@lcadalzo Yes.

**Review by swsuggs — APPROVED** [review]
looks good

**Pull request merged**
